channels:
  targets:
  - [ver228, main]
travis:
  secure:
    BINSTAR_TOKEN: R+d2IBP01umYhdw+BIYDVN2yoO3a7ms/76jNtEsPV3TaxHtsOMQx4+7wN7JzeyYzQ7F0VeBGLVqo5j0n7xy6eVLPcfnbgOAY1DeAzCrxgZPnkIQ6un3XJF4ATr0xS+AevUyDKGcpMqH01t0UvyCJZtOyGskConO6rtYq0sYHGk8eOGTX0/X1NkoahGQ5QhOp76S2Fv0GzhMd2+MTgs+ejMHEYZDG1RGIsbyfDKv2j1rW3WjTJaSI6PuzMEKFnjIvi0Lhq40KiaZz2LpMjtkmpHPrZ98hhzJtroXyzEt6Xbu5+efZkBl4wAKMWCPFhUcUgurWdKvxHN7yZ33Yp1g6sUv2Vl9svNDyk7ExBH1v0PRzZ4zBKRp3rzvLmu9oxPS0urTjxgQsmRSyvCKOUaqnm231MnxDFDIXDLQgijy8n/ImKAhCFYUGC20UIx9rV/x51U0TDhjq6t6Py6iIlPEKfj/Q7hAxP4hwQXew5yy42rRqIvV31blJ34MQWt4avueyfQm8i5VUk/MmeI5g6GSH66qUAYZ9lIm8nBWL1zeBaGrehADo8+9OecNR4WsCf5iJK0+af1ph2/K0Odqq8kmoBOwaTSB5cSkV+9FmuC06tVKRebtzlE+oi4IyJMsLuYu7Da59l/om6mTMnFVjizUfdKQKG4nPjyJZVE2IQf1PzO4=
appveyor:
  secure:
    BINSTAR_TOKEN: h+jxVxRg5GD5kOdyEc0A2Mx3AveqSkLpqYGcmSgdEQRJ/u4li5RjcC4ohMk8i/Kp
