channels:
  targets:
  - [ver228, main]
travis:
  secure:
    BINSTAR_TOKEN: hwVPiqTQhmk9K/LCxoDmLn2UkWOUW69eEgRgfWu6wHl1Nb8XC/6KjR1bwxo81F+7OndOvj4x60XQdbWpz1tGWLpkQQLv2AfuuSrqDvDC9VhSJaqb2XQDuz9y1rr+XS0/KeWn0UwHDlntGklxfAQWBrFl2ZTCiig9ZeaOw73D/ViPIvDCp+ZwNcHO0rOc2vYq/6055VfxqTKW+uRyVsDBtGVeexhpb/9ikBWqbjfbs9SdtiTIEauk1xHEl1kqb0vatwuA8Yv0bBgUT6pXVSeH8YymWRGh4ZraP+YFSyEzZTZgX5HVTRKhOX55YlMmSaE7DqiTZ+0npxr5BH+OMUdNrArBqnr+VZBgr/O+SGMU089WMcmLBAhTUblmRxo5YKFXDr55JknpVcwgYq919/WIM0F2Rwbt0REknmZSAstCCogGJd/7q1LC3WUSA40LRvfaYOLwI2zfEgUU8lvoNm+1kBGZMRN76ODe+3pv76DOGeKridwnoDhRpxlfYjT4sBjtayzypHkPTdFQxTgR5XFg00ISKl3E6U2vbexw0huEGBIxSjxa5/O0deS4+Kh2hh/AekzxFg21CEW8XWAJgnRlWKSVvVQwxLQuKfZHL4HrnXX1muCF7VFeiy/E4TfokoAcNTUKFFmlabr2sQpdBPZsqqJSl4hVu7qQD1hPXFZb+Bo=
appveyor:
  secure:
    BINSTAR_TOKEN: h+jxVxRg5GD5kOdyEc0A2Mx3AveqSkLpqYGcmSgdEQRJ/u4li5RjcC4ohMk8i/Kp
