travis:
  secure:
    BINSTAR_TOKEN: CyFtqpIl3xnL5WqLCZg91aBwM3Rcuoh9H7hl5nDrAiB9b65rvkV2MITXkaMpGE4p7cUnpcQhQVAz1FL2XY2uLXSf1LV04cnOks7M2LfyOONry0Se9S1IqM7dOUChChg5zpIWihyynbVx4IUKto/FCy1EDRdBvqthZW1Lqfvm3plwJpDVsuqObp/EIftPhQZzmt2C9V3qDQ45KA9Z3QBgVRJQj45JYPfTaBaxE/E6hye6/VoIDCtWCMRFe9bf435WhOdyVLc4JKh1UP2j9eRe8byq7SJQOXGTSkIBC5TreylPC1S4MvYkceyAJUTma9q7mh2SLW7/+5JwsoyTJh7fftEL+hSaylHXyFTxuwJGKEF28lm/l7fV7mCNW09/qz2I5KRiwyd4Yg8ME0M4SibPqsb2zXFCxvK6zAVQ5jO9RulBxViDAUuPWw2mb8jUCLrt2IJMxlBKtVR3rtu+IN7VyclqqkPQVD/IGRvt7qiVPf5y3uAIzLCbpx8ARt7xUtbnktvvO0KbSIG70T2Ej54t0FDoV0dTMIIRHg7Wkp4NOeR0n3iHhbOHtpWU+k6frOesYUPQnv3oe2ujTooaF5HPapjM00fy68jj6a2QTfzLMu9ojxX9DnTGXZF00OJYNfc6VL02L0JLUKpzjsm9MpV9UkVh5BWoixtLS2OszGCPQxc=
appveyor:
  secure:
    BINSTAR_TOKEN: h+jxVxRg5GD5kOdyEc0A2Mx3AveqSkLpqYGcmSgdEQRJ/u4li5RjcC4ohMk8i/Kp
